# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20171123_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryVerse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftta_term', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=100)),
                ('verse', models.TextField()),
                ('for_class', models.CharField(choices=[('ECAL', 'Experience of Christ as Life'), ('GE', "God's Economy"), ('GoW', 'God Ordained Way')], max_length=1)),
            ],
        ),
    ]
