# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_memoryverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryverse',
            name='for_class',
            field=models.CharField(choices=[('ECAL', 'Experience of Christ as Life'), ('GE', "God's Economy"), ('GoW', 'God Ordained Way')], max_length=100),
        ),
    ]
